PUTCLOSE con,"_V6_Sets_FAOSTAT_Regions";

$ontext;
GENERAL DESCRIPTION
This file declares the sets where all geographic regions and aggregates thereof as used in FAOSTAT are collected and it defines the hierarchical structure of those
The sources where these sets come from and partly some further information are given at the beginning of each set definition in the code below.

DETAILED TABLE OF CONTENTS
the following sets are declared below:

- 1) Basic sets of all countries and regions as reported in FAOSTAT;

SHORT SUMMARY:
In this code file, the following sets are defined:
Set FAOSTAT_GeographicRegionsCode Country and region codes that may be used in FAOSTAT
Set FAOSTAT_CountriesAndRegions Country and region names that may be used in FAOSTAT
Set FAOSTAT_CountriesAndRegionsWithCode(FAOSTAT_GeographicRegionsCode,FAOSTAT_CountriesAndRegions) Two dimensional set containing all country and region codes and names matched that may be used in FAOSTAT
Set FAOSTAT_Countries(FAOSTAT_CountriesAndRegions) Sub-set containing all country names that may be used in FAOSTAT
Set FAOSTAT_Regions(FAOSTAT_CountriesAndRegions) Sub-set containing all region names that may be used in FAOSTAT
Set FAOSTAT_Continents(FAOSTAT_Regions) Sub-set containing all continent names that may be used in FAOSTAT
Set FAOSTAT_Subcontinents(FAOSTAT_Regions) Sub-set containing all sub-continent names that may be used in FAOSTAT
Set FAOSTAT_DevelopedDevelopingGroups(FAOSTAT_Regions) Sub-set containing developed-developing country groups that may be used in FAOSTAT
Set FAOSTAT_ContinentsSubcontinents(FAOSTAT_Regions,FAOSTAT_CountriesAndRegions) Two dimensional set containing all sub-continents matched to continents
Set FAOSTAT_CountriesInRegions(FAOSTAT_Regions,FAOSTAT_CountriesAndRegions) Two dimensional set containing all regions matched to countries

ATTENTION:
sometimes, when copying from the FAOSTAT csv, "Côte d'Ivoire" is inserted as "CÃ´te d'Ivoire" - thus, check for this and replace where needed
sometimes, this mistake is already present in the csv downloaded from FAOSTAT - thus correct there already, if necessary
furthermore, "Cape verde" is currently spelled as "Cabo verde" - be aware of that and adapt in other datasets where needed.
$offtext;


*MODEL CODE:

****************************************************************************************************************************************************************************************************
****************************************************************************************************************************************************************************************************
*1) Basic sets of all countries and regions as reported in FAOSTAT

Set FAOSTAT_GeographicRegionsCode Country and region codes that may be used in FAOSTAT
*we add two dummy numebrs to have something for "developed countries" and "developing countries" which we add as groups to the FAOSTAT regions, albeit they are not used in FAOSTAT
/1*6000,100000,100001,100002/;

*contains first the set of all countries and regions, then the same set matched with the country and region codes
*where indicated, start/end years were added as comments

Set FAOSTAT_CountriesAndRegions Country and region names that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
*start/end dates refer to the country just ABOVE the data
/
"Afghanistan"
"Africa"
"Albania"
"Algeria"
"American Samoa"
"Americas"
"Angola"
"Antigua and Barbuda"
"Argentina"
"Armenia"
*start: 1992
"Aruba"
"Asia"
"Australia"
"Australia & New Zealand"
"Austria"
"Azerbaijan"
*start: 1992
"Bahamas"
"Bahrain"
"Bangladesh"
"Barbados"
"Belarus"
*start: 1992
"Belgium"
*start: 2000
"Belgium-Luxembourg"
*end: 1999
"Belize"
"Benin"
"Bermuda"
"Bhutan"
"Bolivia (Plurinational State of)"
"Bosnia and Herzegovina"
*start: 1992
"Botswana"
"Brazil"
"British Virgin Islands"
"Brunei Darussalam"
"Bulgaria"
"Burkina Faso"
"Burundi"
"Cabo Verde"
"Cambodia"
"Cameroon"
"Canada"
"Caribbean"
"Cayman Islands"
"Central African Republic"
"Central America"
"Central Asia"
"Chad"
"Chile"
"China"
"China, Hong Kong SAR"
"China, Macao SAR"
"China, mainland"
"China, Taiwan Province of"
"Colombia"
"Comoros"
"Congo"
"Cook Islands"
"Costa Rica"
"Côte d'Ivoire"
"Croatia"
*start: 1992
"Cuba"
"Cyprus"
"Czechia"
*start: 1993
"Czechoslovakia"
*start: 1992
"Democratic People's Republic of Korea"
"Democratic Republic of the Congo"
"Denmark"
"Djibouti"
"Dominica"
"Dominican Republic"
"Eastern Africa"
"Eastern Asia"
"Eastern Europe"
"Ecuador"
"Egypt"
"El Salvador"
"Equatorial Guinea"
"Eritrea"
*start: 1993
"Estonia"
*start: 1992
"Ethiopia"
*start: 1993
"Ethiopia PDR"
*end: 1992
"Europe"
"European Union"
"Falkland Islands (Malvinas)"
"Faroe Islands"
"Fiji"
"Finland"
"France"
"French Polynesia"
"Gabon"
"Gambia"
"Georgia"
*start 1992
"Germany"
"Ghana"
"Greece"
"Grenada"
"Guam"
"Guatemala"
"Guinea"
"Guinea-Bissau"
"Guyana"
"Haiti"
"Honduras"
"Hungary"
"Iceland"
"India"
"Indonesia"
"Iran (Islamic Republic of)"
"Iraq"
"Ireland"
"Israel"
"Italy"
"Jamaica"
"Japan"
"Jordan"
"Kazakhstan"
*start: 1992
"Kenya"
"Kiribati"
"Kuwait"
"Kyrgyzstan"
*start: 1992
"Land Locked Developing Countries"
"Lao People's Democratic Republic"
"Latvia"
*start: 1992
"Least Developed Countries"
"Lebanon"
"Lesotho"
"Liberia"
"Libya"
"Lithuania"
*start: 1992
"Low Income Food Deficit Countries"
"Luxembourg"
*start: 2000
"Madagascar"
"Malawi"
"Malaysia"
"Maldives"
"Mali"
"Malta"
*we added "Marshall Isalnds" albeit it is not in the list downloaded from FAOSTAT - but it is in the data
"Marshall Islands"
"Mauritania"
"Mauritius"
"Melanesia"
"Mexico"
"Micronesia"
"Middle Africa"
"Mongolia"
"Montenegro"
*start: 2006
"Morocco"
"Mozambique"
"Myanmar"
"Namibia"
"Nauru"
"Nepal"
"Net Food Importing Developing Countries"
"Netherlands"
"Netherlands Antilles (former)"
*start: 2010
"New Caledonia"
"New Zealand"
"Nicaragua"
"Niger"
"Nigeria"
"Niue"
"Norfolk Island"
"Northern Africa"
"Northern America"
"Northern Europe"
"Norway"
"Occupied Palestinian Territory"
"Oceania"
"Oman"
"Pacific Islands Trust Territory"
*start: 1990
"Pakistan"
"Panama"
"Papua New Guinea"
"Paraguay"
"Peru"
"Philippines"
"Poland"
"Polynesia"
"Portugal"
"Qatar"
"Republic of Korea"
"Republic of Moldova"
*start: 1992
"Romania"
"Russian Federation"
*start: 1992
"Rwanda"
"Saint Kitts and Nevis"
"Saint Lucia"
"Saint Pierre and Miquelon"
"Saint Vincent and the Grenadines"
"Samoa"
"Sao Tome and Principe"
"Saudi Arabia"
"Senegal"
"Serbia"
*start 2006
"Serbia and Montenegro"
*start: 1992; end: 2005
"Seychelles"
"Sierra Leone"
"Singapore"
"Slovakia"
*start: 1993
"Slovenia"
*start: 1992
"Small Island Developing States"
"Solomon Islands"
"Somalia"
"South Africa"
"South America"
"South Sudan"
*start: 2012
"South-Eastern Asia"
"Southern Africa"
"Southern Asia"
"Southern Europe"
"Spain"
"Sri Lanka"
"Sudan"
*start: 2012
*"Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Suriname"
"Swaziland"
"Sweden"
"Switzerland"
"Syrian Arab Republic"
"Tajikistan"
*start: 1992
"Thailand"
"The former Yugoslav Republic of Macedonia"
*start: 1992
"Timor-Leste"
"Togo"
"Tonga"
"Trinidad and Tobago"
"Tunisia"
"Turkey"
"Turkmenistan"
*start: 1992
"Tuvalu"
"Uganda"
"Ukraine"
*startt: 1992
"United Arab Emirates"
"United Kingdom"
"United Republic of Tanzania"
"United States of America"
"Uruguay"
"USSR"
*end: 1991
"Uzbekistan"
*start: 1992
"Vanuatu"
"Venezuela (Bolivarian Republic of)"
"Viet Nam"
"Western Africa"
"Western Asia"
"Western Europe"
"World"
"Yemen"
"Yugoslav SFR"
*end: 1991
"Zambia"
"Zimbabwe"
*the following is a categorisation currently not used officially in FAOSTAT - but we need it for certain assignments and thus introduce it to this set
"Developed Countries"
"Developing Countries"
"Indian Subcontinent"

/;


Set FAOSTAT_CountriesAndRegionsWithCode(FAOSTAT_GeographicRegionsCode,FAOSTAT_CountriesAndRegions) Two dimensional set containing all country and region codes and names matched that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
/
*"Item Code"."Item"
2."Afghanistan"
5100."Africa"
3."Albania"
4."Algeria"
5."American Samoa"
5200."Americas"
7."Angola"
8."Antigua and Barbuda"
9."Argentina"
1."Armenia"
*start: 1992
22."Aruba"
5300."Asia"
10."Australia"
5501."Australia & New Zealand"
11."Austria"
52."Azerbaijan"
*start: 1992
12."Bahamas"
13."Bahrain"
16."Bangladesh"
14."Barbados"
57."Belarus"
*start: 1992
255."Belgium"
*start: 2000
15."Belgium-Luxembourg"
*end: 1999
23."Belize"
53."Benin"
17."Bermuda"
18."Bhutan"
19."Bolivia (Plurinational State of)"
80."Bosnia and Herzegovina"
*start: 1992
20."Botswana"
21."Brazil"
239."British Virgin Islands"
26."Brunei Darussalam"
27."Bulgaria"
233."Burkina Faso"
29."Burundi"
35."Cabo Verde"
115."Cambodia"
32."Cameroon"
33."Canada"
5206."Caribbean"
36."Cayman Islands"
37."Central African Republic"
5204."Central America"
5301."Central Asia"
39."Chad"
40."Chile"
351."China"
96."China, Hong Kong SAR"
128."China, Macao SAR"
41."China, mainland"
214."China, Taiwan Province of"
44."Colombia"
45."Comoros"
46."Congo"
47."Cook Islands"
48."Costa Rica"
107."Côte d'Ivoire"
98."Croatia"
*start: 1992
49."Cuba"
50."Cyprus"
167."Czechia"
*start: 1993
51."Czechoslovakia"
*end: 1992
116."Democratic People's Republic of Korea"
250."Democratic Republic of the Congo"
54."Denmark"
72."Djibouti"
55."Dominica"
56."Dominican Republic"
5101."Eastern Africa"
5302."Eastern Asia"
5401."Eastern Europe"
58."Ecuador"
59."Egypt"
60."El Salvador"
61."Equatorial Guinea"
178."Eritrea"
*start: 1993
63."Estonia"
*start: 1992
238."Ethiopia"
*start: 1993
62."Ethiopia PDR"
*end: 1992
5400."Europe"
5706."European Union"
65."Falkland Islands (Malvinas)"
64."Faroe Islands"
66."Fiji"
67."Finland"
68."France"
70."French Polynesia"
74."Gabon"
75."Gambia"
73."Georgia"
*start 1992
79."Germany"
81."Ghana"
84."Greece"
86."Grenada"
88."Guam"
89."Guatemala"
90."Guinea"
175."Guinea-Bissau"
91."Guyana"
93."Haiti"
95."Honduras"
97."Hungary"
99."Iceland"
100."India"
101."Indonesia"
102."Iran (Islamic Republic of)"
103."Iraq"
104."Ireland"
105."Israel"
106."Italy"
109."Jamaica"
110."Japan"
112."Jordan"
108."Kazakhstan"
*start: 1992
114."Kenya"
83."Kiribati"
118."Kuwait"
113."Kyrgyzstan"
*start: 1992
5802."Land Locked Developing Countries"
120."Lao People's Democratic Republic"
119."Latvia"
*start: 1992
5801."Least Developed Countries"
121."Lebanon"
122."Lesotho"
123."Liberia"
124."Libya"
126."Lithuania"
*start: 1992
5815."Low Income Food Deficit Countries"
256."Luxembourg"
*start: 2000
129."Madagascar"
130."Malawi"
131."Malaysia"
132."Maldives"
133."Mali"
134."Malta"
127."Marshall Islands"
136."Mauritania"
137."Mauritius"
5502."Melanesia"
138."Mexico"
5503."Micronesia"
5102."Middle Africa"
141."Mongolia"
273."Montenegro"
*start: 2006
143."Morocco"
144."Mozambique"
28."Myanmar"
147."Namibia"
148."Nauru"
149."Nepal"
5817."Net Food Importing Developing Countries"
150."Netherlands"
151."Netherlands Antilles (former)"
*start: 2010
153."New Caledonia"
156."New Zealand"
157."Nicaragua"
158."Niger"
159."Nigeria"
160."Niue"
161."Norfolk Island"
5103."Northern Africa"
5203."Northern America"
5402."Northern Europe"
162."Norway"
299."Occupied Palestinian Territory"
5500."Oceania"
221."Oman"
164."Pacific Islands Trust Territory"
*start: 1990
165."Pakistan"
166."Panama"
168."Papua New Guinea"
169."Paraguay"
170."Peru"
171."Philippines"
173."Poland"
5504."Polynesia"
174."Portugal"
179."Qatar"
117."Republic of Korea"
146."Republic of Moldova"
*start: 1992
183."Romania"
185."Russian Federation"
*start: 1992
184."Rwanda"
188."Saint Kitts and Nevis"
189."Saint Lucia"
190."Saint Pierre and Miquelon"
191."Saint Vincent and the Grenadines"
244."Samoa"
193."Sao Tome and Principe"
194."Saudi Arabia"
195."Senegal"
272."Serbia"
*start 2006
186."Serbia and Montenegro"
*start: 1992; end: 2005
196."Seychelles"
197."Sierra Leone"
200."Singapore"
199."Slovakia"
*start: 1993
198."Slovenia"
*start: 1992
5803."Small Island Developing States"
25."Solomon Islands"
201."Somalia"
202."South Africa"
5207."South America"
277."South Sudan"
*start: 2012
5304."South-Eastern Asia"
5104."Southern Africa"
5303."Southern Asia"
5403."Southern Europe"
203."Spain"
38."Sri Lanka"
276."Sudan"
*start: 2012
*206."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
207."Suriname"
209."Swaziland"
210."Sweden"
211."Switzerland"
212."Syrian Arab Republic"
208."Tajikistan"
*start: 1992
216."Thailand"
154."The former Yugoslav Republic of Macedonia"
*start: 1992
176."Timor-Leste"
217."Togo"
219."Tonga"
220."Trinidad and Tobago"
222."Tunisia"
223."Turkey"
213."Turkmenistan"
*start: 1992
227."Tuvalu"
226."Uganda"
230."Ukraine"
*startt: 1992
225."United Arab Emirates"
229."United Kingdom"
215."United Republic of Tanzania"
231."United States of America"
234."Uruguay"
228."USSR"
*end: 1991
235."Uzbekistan"
*start: 1992
155."Vanuatu"
236."Venezuela (Bolivarian Republic of)"
237."Viet Nam"
5105."Western Africa"
5305."Western Asia"
5404."Western Europe"
5000."World"
249."Yemen"
248."Yugoslav SFR"
*end: 1991
251."Zambia"
181."Zimbabwe"

*added to this set, albeit not included by FAOSTAT - but we need this two groups as well
100000."Developed Countries"
100001."Developing Countries"
100002."Indian Subcontinent"

/;


Set FAOSTAT_Countries(FAOSTAT_CountriesAndRegions) Sub-set containing all country names that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
*the entries with code below 1000
/
"Afghanistan"
"Albania"
"Algeria"
"American Samoa"
"Angola"
"Antigua and Barbuda"
"Argentina"
"Armenia"
*start: 1992
"Aruba"
"Australia"
"Austria"
"Azerbaijan"
*start: 1992
"Bahamas"
"Bahrain"
"Bangladesh"
"Barbados"
"Belarus"
*start: 1992
"Belgium"
*start: 2000
"Belgium-Luxembourg"
*end: 1999
"Belize"
"Benin"
"Bermuda"
"Bhutan"
"Bolivia (Plurinational State of)"
"Bosnia and Herzegovina"
*start: 1992
"Botswana"
"Brazil"
"British Virgin Islands"
"Brunei Darussalam"
"Bulgaria"
"Burkina Faso"
"Burundi"
"Cabo Verde"
"Cambodia"
"Cameroon"
"Canada"
"Cayman Islands"
"Central African Republic"
"Chad"
"Chile"
"China"
*"China, Hong Kong SAR"
*"China, Macao SAR"
*"China, mainland"
*"China, Taiwan Province of"
"Colombia"
"Comoros"
"Congo"
"Cook Islands"
"Costa Rica"
"Côte d'Ivoire"
"Croatia"
*start: 1992
"Cuba"
"Cyprus"
"Czechia"
*start: 1993
"Czechoslovakia"
*end: 1992
"Democratic People's Republic of Korea"
"Democratic Republic of the Congo"
"Denmark"
"Djibouti"
"Dominica"
"Dominican Republic"
"Ecuador"
"Egypt"
"El Salvador"
"Equatorial Guinea"
"Eritrea"
*start: 1993
"Estonia"
*start: 1992
"Ethiopia"
*start: 1993
"Ethiopia PDR"
*end: 1992
"Falkland Islands (Malvinas)"
"Faroe Islands"
"Fiji"
"Finland"
"France"
"French Polynesia"
"Gabon"
"Gambia"
"Georgia"
*start 1992
"Germany"
"Ghana"
"Greece"
"Grenada"
"Guam"
"Guatemala"
"Guinea"
"Guinea-Bissau"
"Guyana"
"Haiti"
"Honduras"
"Hungary"
"Iceland"
"India"
"Indonesia"
"Iran (Islamic Republic of)"
"Iraq"
"Ireland"
"Israel"
"Italy"
"Jamaica"
"Japan"
"Jordan"
"Kazakhstan"
*start: 1992
"Kenya"
"Kiribati"
"Kuwait"
"Kyrgyzstan"
*start: 1992
"Lao People's Democratic Republic"
"Latvia"
*start: 1992
"Lebanon"
"Lesotho"
"Liberia"
"Libya"
"Lithuania"
*start: 1992
"Luxembourg"
*start: 2000
"Madagascar"
"Malawi"
"Malaysia"
"Maldives"
"Mali"
"Malta"
"Marshall Islands"
"Mauritania"
"Mauritius"
"Mexico"
"Mongolia"
"Montenegro"
*start: 2006
"Morocco"
"Mozambique"
"Myanmar"
"Namibia"
"Nauru"
"Nepal"
"Netherlands"
"Netherlands Antilles (former)"
*start: 2010
"New Caledonia"
"New Zealand"
"Nicaragua"
"Niger"
"Nigeria"
"Niue"
"Norfolk Island"
"Norway"
"Occupied Palestinian Territory"
"Oman"
"Pacific Islands Trust Territory"
*start: 1990
"Pakistan"
"Panama"
"Papua New Guinea"
"Paraguay"
"Peru"
"Philippines"
"Poland"
"Portugal"
"Qatar"
"Republic of Korea"
"Republic of Moldova"
*start: 1992
"Romania"
"Russian Federation"
*start: 1992
"Rwanda"
"Saint Kitts and Nevis"
"Saint Lucia"
"Saint Pierre and Miquelon"
"Saint Vincent and the Grenadines"
"Samoa"
"Sao Tome and Principe"
"Saudi Arabia"
"Senegal"
"Serbia"
*start 2006
"Serbia and Montenegro"
*start: 1992; end: 2005
"Seychelles"
"Sierra Leone"
"Singapore"
"Slovakia"
*start: 1993
"Slovenia"
*start: 1992
"Solomon Islands"
"Somalia"
"South Africa"
"South Sudan"
*start: 2012
"Spain"
"Sri Lanka"
"Sudan"
*start: 2012
*"Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Suriname"
"Swaziland"
"Sweden"
"Switzerland"
"Syrian Arab Republic"
"Tajikistan"
*start: 1992
"Thailand"
"The former Yugoslav Republic of Macedonia"
*start: 1992
"Timor-Leste"
"Togo"
"Tonga"
"Trinidad and Tobago"
"Tunisia"
"Turkey"
"Turkmenistan"
*start: 1992
"Tuvalu"
"Uganda"
"Ukraine"
*start: 1992
"United Arab Emirates"
"United Kingdom"
"United Republic of Tanzania"
"United States of America"
"Uruguay"
"USSR"
*end: 1991
"Uzbekistan"
*start: 1992
"Vanuatu"
"Venezuela (Bolivarian Republic of)"
"Viet Nam"
"Yemen"
"Yugoslav SFR"
*end: 1991
"Zambia"
"Zimbabwe"
/;

Set FAOSTAT_Regions(FAOSTAT_CountriesAndRegions) Sub-set containing all region names that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
*the entries with code above 5000
/
"World"

"Africa"
"Americas"
"Asia"
"Europe"
"Oceania"

"Eastern Africa"
"Middle Africa"
"Northern Africa"
"Southern Africa"
"Western Africa"

"Caribbean"
"Central America"
"Northern America"
"South America"

"Central Asia"
"Eastern Asia"
"South-Eastern Asia"
"Southern Asia"
"Western Asia"

"Eastern Europe"
"Northern Europe"
"Southern Europe"
"Western Europe"

"Australia & New Zealand"
"Melanesia"
"Micronesia"
"Polynesia"


"European Union"
"Land Locked Developing Countries"
"Least Developed Countries"
"Low Income Food Deficit Countries"
"Net Food Importing Developing Countries"
"Small Island Developing States"


*the following are added to the groups used by FAOSTAT, as we need them as well already when filing in data (from IPCC, for example)
"Developed Countries"
"Developing Countries"
"Indian Subcontinent"
/;


Set FAOSTAT_Continents(FAOSTAT_Regions) Sub-set containing all continent names that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
/
"Africa"
"Americas"
"Asia"
"Europe"
"Oceania"
/;


Set FAOSTAT_Subcontinents(FAOSTAT_Regions) Sub-set containing all sub-continent names that may be used in FAOSTAT
*as contained in the file FAOSTAT_CountryAndRegionsDefinition_11_12_2017.csv
/
"Eastern Africa"
"Middle Africa"
"Northern Africa"
"Southern Africa"
"Western Africa"

"Caribbean"
"Central America"
"Northern America"
"South America"

"Central Asia"
"Eastern Asia"
"South-Eastern Asia"
"Southern Asia"
"Western Asia"

"Eastern Europe"
"Northern Europe"
"Southern Europe"
"Western Europe"

"Australia & New Zealand"
"Melanesia"
"Micronesia"
"Polynesia"
/;


Set FAOSTAT_DevelopedDevelopingGroups(FAOSTAT_Regions) Sub-set containing developed-developing country groups that may be used in FAOSTAT
/
"Developed Countries"
"Developing Countries"
/


Set FAOSTAT_ContinentsSubcontinents(FAOSTAT_Regions,FAOSTAT_CountriesAndRegions) Two dimensional set containing all sub-continents matched to continents
/
"Africa"."Eastern Africa"
"Africa"."Middle Africa"
"Africa"."Northern Africa"
"Africa"."Southern Africa"
"Africa"."Western Africa"

"Americas"."Caribbean"
"Americas"."Central America"
"Americas"."Northern America"
"Americas"."South America"

"Asia"."Central Asia"
"Asia"."Eastern Asia"
"Asia"."South-Eastern Asia"
"Asia"."Southern Asia"
"Asia"."Western Asia"

"Europe"."Eastern Europe"
"Europe"."Northern Europe"
"Europe"."Southern Europe"
"Europe"."Western Europe"

"Oceania"."Australia & New Zealand"
"Oceania"."Melanesia"
"Oceania"."Micronesia"
"Oceania"."Polynesia"
/;


Set FAOSTAT_CountriesInRegions(FAOSTAT_Regions,FAOSTAT_CountriesAndRegions) Two dimensional set containing all regions matched to countries
*as contained in the file FAOSTAT_CountryGroupDefinition_11_12_2017.csv
/
"Africa"."Algeria"
"Africa"."Angola"
"Africa"."Benin"
"Africa"."Botswana"
"Africa"."Burkina Faso"
"Africa"."Burundi"
"Africa"."Cabo Verde"
"Africa"."Cameroon"
"Africa"."Central African Republic"
"Africa"."Chad"
"Africa"."Comoros"
"Africa"."Congo"
"Africa"."Côte d'Ivoire"
"Africa"."Democratic Republic of the Congo"
"Africa"."Djibouti"
"Africa"."Egypt"
"Africa"."Equatorial Guinea"
"Africa"."Eritrea"
"Africa"."Ethiopia"
"Africa"."Ethiopia PDR"
"Africa"."Gabon"
"Africa"."Gambia"
"Africa"."Ghana"
"Africa"."Guinea"
"Africa"."Guinea-Bissau"
"Africa"."Kenya"
"Africa"."Lesotho"
"Africa"."Liberia"
"Africa"."Libya"
"Africa"."Madagascar"
"Africa"."Malawi"
"Africa"."Mali"
"Africa"."Mauritania"
"Africa"."Mauritius"
"Africa"."Morocco"
"Africa"."Mozambique"
"Africa"."Namibia"
"Africa"."Niger"
"Africa"."Nigeria"
"Africa"."Rwanda"
"Africa"."Sao Tome and Principe"
"Africa"."Senegal"
"Africa"."Seychelles"
"Africa"."Sierra Leone"
"Africa"."Somalia"
"Africa"."South Africa"
"Africa"."South Sudan"
"Africa"."Sudan"
*"Africa"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Africa"."Swaziland"
"Africa"."Togo"
"Africa"."Tunisia"
"Africa"."Uganda"
"Africa"."United Republic of Tanzania"
"Africa"."Zambia"
"Africa"."Zimbabwe"
"Americas"."Antigua and Barbuda"
"Americas"."Argentina"
"Americas"."Aruba"
"Americas"."Bahamas"
"Americas"."Barbados"
"Americas"."Belize"
"Americas"."Bermuda"
"Americas"."Bolivia (Plurinational State of)"
"Americas"."Brazil"
"Americas"."British Virgin Islands"
"Americas"."Canada"
"Americas"."Cayman Islands"
"Americas"."Chile"
"Americas"."Colombia"
"Americas"."Costa Rica"
"Americas"."Cuba"
"Americas"."Dominica"
"Americas"."Dominican Republic"
"Americas"."Ecuador"
"Americas"."El Salvador"
"Americas"."Falkland Islands (Malvinas)"
"Americas"."Grenada"
"Americas"."Guatemala"
"Americas"."Guyana"
"Americas"."Haiti"
"Americas"."Honduras"
"Americas"."Jamaica"
"Americas"."Mexico"
"Americas"."Netherlands Antilles (former)"
"Americas"."Nicaragua"
"Americas"."Panama"
"Americas"."Paraguay"
"Americas"."Peru"
"Americas"."Saint Kitts and Nevis"
"Americas"."Saint Lucia"
"Americas"."Saint Pierre and Miquelon"
"Americas"."Saint Vincent and the Grenadines"
"Americas"."Suriname"
"Americas"."Trinidad and Tobago"
"Americas"."United States of America"
"Americas"."Uruguay"
"Americas"."Venezuela (Bolivarian Republic of)"
"Asia"."Afghanistan"
"Asia"."Armenia"
"Asia"."Azerbaijan"
"Asia"."Bahrain"
"Asia"."Bangladesh"
"Asia"."Bhutan"
"Asia"."Brunei Darussalam"
"Asia"."Cambodia"
"Asia"."China"
*"Asia"."China, Hong Kong SAR"
*"Asia"."China, Macao SAR"
*"Asia"."China, mainland"
*"Asia"."China, Taiwan Province of"
"Asia"."Cyprus"
"Asia"."Democratic People's Republic of Korea"
"Asia"."Georgia"
"Asia"."India"
"Asia"."Indonesia"
"Asia"."Iran (Islamic Republic of)"
"Asia"."Iraq"
"Asia"."Israel"
"Asia"."Japan"
"Asia"."Jordan"
"Asia"."Kazakhstan"
"Asia"."Kuwait"
"Asia"."Kyrgyzstan"
"Asia"."Lao People's Democratic Republic"
"Asia"."Lebanon"
"Asia"."Malaysia"
"Asia"."Maldives"
"Asia"."Mongolia"
"Asia"."Myanmar"
"Asia"."Nepal"
"Asia"."Occupied Palestinian Territory"
"Asia"."Oman"
"Asia"."Pakistan"
"Asia"."Philippines"
"Asia"."Qatar"
"Asia"."Republic of Korea"
"Asia"."Saudi Arabia"
"Asia"."Singapore"
"Asia"."Sri Lanka"
"Asia"."Syrian Arab Republic"
"Asia"."Tajikistan"
"Asia"."Thailand"
"Asia"."Timor-Leste"
"Asia"."Turkey"
"Asia"."Turkmenistan"
"Asia"."United Arab Emirates"
"Asia"."Uzbekistan"
"Asia"."Viet Nam"
"Asia"."Yemen"
"Australia & New Zealand"."Australia"
"Australia & New Zealand"."New Zealand"
"Australia & New Zealand"."Norfolk Island"
"Caribbean"."Antigua and Barbuda"
"Caribbean"."Aruba"
"Caribbean"."Bahamas"
"Caribbean"."Barbados"
"Caribbean"."British Virgin Islands"
"Caribbean"."Cayman Islands"
"Caribbean"."Cuba"
"Caribbean"."Dominica"
"Caribbean"."Dominican Republic"
"Caribbean"."Grenada"
"Caribbean"."Haiti"
"Caribbean"."Jamaica"
"Caribbean"."Netherlands Antilles (former)"
"Caribbean"."Saint Kitts and Nevis"
"Caribbean"."Saint Lucia"
"Caribbean"."Saint Vincent and the Grenadines"
"Caribbean"."Trinidad and Tobago"
"Central America"."Belize"
"Central America"."Costa Rica"
"Central America"."El Salvador"
"Central America"."Guatemala"
"Central America"."Honduras"
"Central America"."Mexico"
"Central America"."Nicaragua"
"Central America"."Panama"
"Central Asia"."Kazakhstan"
"Central Asia"."Kyrgyzstan"
"Central Asia"."Tajikistan"
"Central Asia"."Turkmenistan"
"Central Asia"."Uzbekistan"
"Eastern Africa"."Burundi"
"Eastern Africa"."Comoros"
"Eastern Africa"."Djibouti"
"Eastern Africa"."Eritrea"
"Eastern Africa"."Ethiopia"
"Eastern Africa"."Ethiopia PDR"
"Eastern Africa"."Kenya"
"Eastern Africa"."Madagascar"
"Eastern Africa"."Malawi"
"Eastern Africa"."Mauritius"
"Eastern Africa"."Mozambique"
"Eastern Africa"."Rwanda"
"Eastern Africa"."Seychelles"
"Eastern Africa"."Somalia"
"Eastern Africa"."South Sudan"
"Eastern Africa"."Uganda"
"Eastern Africa"."United Republic of Tanzania"
"Eastern Africa"."Zambia"
"Eastern Africa"."Zimbabwe"
"Eastern Asia"."China"
*"Eastern Asia"."China, Hong Kong SAR"
*"Eastern Asia"."China, Macao SAR"
*"Eastern Asia"."China, mainland"
*"Eastern Asia"."China, Taiwan Province of"
"Eastern Asia"."Democratic People's Republic of Korea"
"Eastern Asia"."Japan"
"Eastern Asia"."Mongolia"
"Eastern Asia"."Republic of Korea"
"Eastern Europe"."Belarus"
"Eastern Europe"."Bulgaria"
"Eastern Europe"."Czechia"
"Eastern Europe"."Czechoslovakia"
"Eastern Europe"."Hungary"
"Eastern Europe"."Poland"
"Eastern Europe"."Republic of Moldova"
"Eastern Europe"."Romania"
"Eastern Europe"."Russian Federation"
"Eastern Europe"."Slovakia"
"Eastern Europe"."Ukraine"
"Eastern Europe"."USSR"
"Europe"."Albania"
"Europe"."Austria"
"Europe"."Belarus"
"Europe"."Belgium"
"Europe"."Belgium-Luxembourg"
"Europe"."Bosnia and Herzegovina"
"Europe"."Bulgaria"
"Europe"."Croatia"
"Europe"."Czechia"
"Europe"."Czechoslovakia"
"Europe"."Denmark"
"Europe"."Estonia"
"Europe"."Faroe Islands"
"Europe"."Finland"
"Europe"."France"
"Europe"."Germany"
"Europe"."Greece"
"Europe"."Hungary"
"Europe"."Iceland"
"Europe"."Ireland"
"Europe"."Italy"
"Europe"."Latvia"
"Europe"."Lithuania"
"Europe"."Luxembourg"
"Europe"."Malta"
"Europe"."Montenegro"
"Europe"."Netherlands"
"Europe"."Norway"
"Europe"."Poland"
"Europe"."Portugal"
"Europe"."Republic of Moldova"
"Europe"."Romania"
"Europe"."Russian Federation"
"Europe"."Serbia"
"Europe"."Serbia and Montenegro"
"Europe"."Slovakia"
"Europe"."Slovenia"
"Europe"."Spain"
"Europe"."Sweden"
"Europe"."Switzerland"
"Europe"."The former Yugoslav Republic of Macedonia"
"Europe"."Ukraine"
"Europe"."United Kingdom"
"Europe"."USSR"
"Europe"."Yugoslav SFR"
"European Union"."Austria"
"European Union"."Belgium"
"European Union"."Belgium-Luxembourg"
"European Union"."Bulgaria"
"European Union"."Croatia"
"European Union"."Cyprus"
"European Union"."Czechia"
"European Union"."Denmark"
"European Union"."Estonia"
"European Union"."Finland"
"European Union"."France"
"European Union"."Germany"
"European Union"."Greece"
"European Union"."Hungary"
"European Union"."Ireland"
"European Union"."Italy"
"European Union"."Latvia"
"European Union"."Lithuania"
"European Union"."Luxembourg"
"European Union"."Malta"
"European Union"."Netherlands"
"European Union"."Poland"
"European Union"."Portugal"
"European Union"."Romania"
"European Union"."Slovakia"
"European Union"."Slovenia"
"European Union"."Spain"
"European Union"."Sweden"
"European Union"."United Kingdom"
"Land Locked Developing Countries"."Afghanistan"
"Land Locked Developing Countries"."Armenia"
"Land Locked Developing Countries"."Azerbaijan"
"Land Locked Developing Countries"."Bhutan"
"Land Locked Developing Countries"."Bolivia (Plurinational State of)"
"Land Locked Developing Countries"."Botswana"
"Land Locked Developing Countries"."Burkina Faso"
"Land Locked Developing Countries"."Burundi"
"Land Locked Developing Countries"."Central African Republic"
"Land Locked Developing Countries"."Chad"
"Land Locked Developing Countries"."Ethiopia"
"Land Locked Developing Countries"."Kazakhstan"
"Land Locked Developing Countries"."Kyrgyzstan"
"Land Locked Developing Countries"."Lao People's Democratic Republic"
"Land Locked Developing Countries"."Lesotho"
"Land Locked Developing Countries"."Malawi"
"Land Locked Developing Countries"."Mali"
"Land Locked Developing Countries"."Mongolia"
"Land Locked Developing Countries"."Nepal"
"Land Locked Developing Countries"."Niger"
"Land Locked Developing Countries"."Paraguay"
"Land Locked Developing Countries"."Republic of Moldova"
"Land Locked Developing Countries"."Rwanda"
"Land Locked Developing Countries"."South Sudan"
"Land Locked Developing Countries"."Swaziland"
"Land Locked Developing Countries"."Tajikistan"
"Land Locked Developing Countries"."The former Yugoslav Republic of Macedonia"
"Land Locked Developing Countries"."Turkmenistan"
"Land Locked Developing Countries"."Uganda"
"Land Locked Developing Countries"."Uzbekistan"
"Land Locked Developing Countries"."Zambia"
"Land Locked Developing Countries"."Zimbabwe"
"Least Developed Countries"."Afghanistan"
"Least Developed Countries"."Angola"
"Least Developed Countries"."Bangladesh"
"Least Developed Countries"."Benin"
"Least Developed Countries"."Bhutan"
"Least Developed Countries"."Burkina Faso"
"Least Developed Countries"."Burundi"
"Least Developed Countries"."Cambodia"
"Least Developed Countries"."Central African Republic"
"Least Developed Countries"."Chad"
"Least Developed Countries"."Comoros"
"Least Developed Countries"."Democratic Republic of the Congo"
"Least Developed Countries"."Djibouti"
"Least Developed Countries"."Equatorial Guinea"
"Least Developed Countries"."Eritrea"
"Least Developed Countries"."Ethiopia"
"Least Developed Countries"."Ethiopia PDR"
"Least Developed Countries"."Gambia"
"Least Developed Countries"."Guinea"
"Least Developed Countries"."Guinea-Bissau"
"Least Developed Countries"."Haiti"
"Least Developed Countries"."Kiribati"
"Least Developed Countries"."Lao People's Democratic Republic"
"Least Developed Countries"."Lesotho"
"Least Developed Countries"."Liberia"
"Least Developed Countries"."Madagascar"
"Least Developed Countries"."Malawi"
"Least Developed Countries"."Mali"
"Least Developed Countries"."Mauritania"
"Least Developed Countries"."Mozambique"
"Least Developed Countries"."Myanmar"
"Least Developed Countries"."Nepal"
"Least Developed Countries"."Niger"
"Least Developed Countries"."Rwanda"
"Least Developed Countries"."Sao Tome and Principe"
"Least Developed Countries"."Senegal"
"Least Developed Countries"."Sierra Leone"
"Least Developed Countries"."Solomon Islands"
"Least Developed Countries"."Somalia"
"Least Developed Countries"."South Sudan"
"Least Developed Countries"."Sudan"
*"Least Developed Countries"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Least Developed Countries"."Timor-Leste"
"Least Developed Countries"."Togo"
"Least Developed Countries"."Tuvalu"
"Least Developed Countries"."Uganda"
"Least Developed Countries"."United Republic of Tanzania"
"Least Developed Countries"."Vanuatu"
"Least Developed Countries"."Yemen"
"Least Developed Countries"."Zambia"
"Low Income Food Deficit Countries"."Afghanistan"
"Low Income Food Deficit Countries"."Bangladesh"
"Low Income Food Deficit Countries"."Benin"
"Low Income Food Deficit Countries"."Burkina Faso"
"Low Income Food Deficit Countries"."Burundi"
"Low Income Food Deficit Countries"."Cameroon"
"Low Income Food Deficit Countries"."Central African Republic"
"Low Income Food Deficit Countries"."Chad"
"Low Income Food Deficit Countries"."Comoros"
"Low Income Food Deficit Countries"."Côte d'Ivoire"
"Low Income Food Deficit Countries"."Democratic People's Republic of Korea"
"Low Income Food Deficit Countries"."Democratic Republic of the Congo"
"Low Income Food Deficit Countries"."Djibouti"
"Low Income Food Deficit Countries"."Eritrea"
"Low Income Food Deficit Countries"."Ethiopia"
"Low Income Food Deficit Countries"."Ethiopia PDR"
"Low Income Food Deficit Countries"."Gambia"
"Low Income Food Deficit Countries"."Ghana"
"Low Income Food Deficit Countries"."Guinea"
"Low Income Food Deficit Countries"."Guinea-Bissau"
"Low Income Food Deficit Countries"."Haiti"
"Low Income Food Deficit Countries"."India"
"Low Income Food Deficit Countries"."Kenya"
"Low Income Food Deficit Countries"."Kyrgyzstan"
"Low Income Food Deficit Countries"."Lesotho"
"Low Income Food Deficit Countries"."Liberia"
"Low Income Food Deficit Countries"."Madagascar"
"Low Income Food Deficit Countries"."Malawi"
"Low Income Food Deficit Countries"."Mali"
"Low Income Food Deficit Countries"."Mauritania"
"Low Income Food Deficit Countries"."Mozambique"
"Low Income Food Deficit Countries"."Nepal"
"Low Income Food Deficit Countries"."Nicaragua"
"Low Income Food Deficit Countries"."Niger"
"Low Income Food Deficit Countries"."Nigeria"
"Low Income Food Deficit Countries"."Pakistan"
"Low Income Food Deficit Countries"."Papua New Guinea"
"Low Income Food Deficit Countries"."Rwanda"
"Low Income Food Deficit Countries"."Sao Tome and Principe"
"Low Income Food Deficit Countries"."Senegal"
"Low Income Food Deficit Countries"."Sierra Leone"
"Low Income Food Deficit Countries"."Solomon Islands"
"Low Income Food Deficit Countries"."Somalia"
"Low Income Food Deficit Countries"."South Sudan"
"Low Income Food Deficit Countries"."Sudan"
*"Low Income Food Deficit Countries"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Low Income Food Deficit Countries"."Syrian Arab Republic"
"Low Income Food Deficit Countries"."Tajikistan"
"Low Income Food Deficit Countries"."Togo"
"Low Income Food Deficit Countries"."Uganda"
"Low Income Food Deficit Countries"."United Republic of Tanzania"
"Low Income Food Deficit Countries"."Uzbekistan"
"Low Income Food Deficit Countries"."Yemen"
"Low Income Food Deficit Countries"."Zimbabwe"
"Melanesia"."Fiji"
"Melanesia"."New Caledonia"
"Melanesia"."Papua New Guinea"
"Melanesia"."Solomon Islands"
"Melanesia"."Vanuatu"
"Micronesia"."Guam"
"Micronesia"."Kiribati"
"Micronesia"."Marshall Islands"
"Micronesia"."Nauru"
"Micronesia"."Pacific Islands Trust Territory"
"Middle Africa"."Angola"
"Middle Africa"."Cameroon"
"Middle Africa"."Central African Republic"
"Middle Africa"."Chad"
"Middle Africa"."Congo"
"Middle Africa"."Democratic Republic of the Congo"
"Middle Africa"."Equatorial Guinea"
"Middle Africa"."Gabon"
"Middle Africa"."Sao Tome and Principe"
"Net Food Importing Developing Countries"."Afghanistan"
"Net Food Importing Developing Countries"."Angola"
"Net Food Importing Developing Countries"."Antigua and Barbuda"
"Net Food Importing Developing Countries"."Bangladesh"
"Net Food Importing Developing Countries"."Barbados"
"Net Food Importing Developing Countries"."Benin"
"Net Food Importing Developing Countries"."Bhutan"
"Net Food Importing Developing Countries"."Botswana"
"Net Food Importing Developing Countries"."Burkina Faso"
"Net Food Importing Developing Countries"."Burundi"
"Net Food Importing Developing Countries"."Cambodia"
"Net Food Importing Developing Countries"."Central African Republic"
"Net Food Importing Developing Countries"."Chad"
"Net Food Importing Developing Countries"."Comoros"
"Net Food Importing Developing Countries"."Côte d'Ivoire"
"Net Food Importing Developing Countries"."Cuba"
"Net Food Importing Developing Countries"."Democratic Republic of the Congo"
"Net Food Importing Developing Countries"."Djibouti"
"Net Food Importing Developing Countries"."Dominica"
"Net Food Importing Developing Countries"."Dominican Republic"
"Net Food Importing Developing Countries"."Egypt"
"Net Food Importing Developing Countries"."El Salvador"
"Net Food Importing Developing Countries"."Equatorial Guinea"
"Net Food Importing Developing Countries"."Eritrea"
"Net Food Importing Developing Countries"."Ethiopia"
"Net Food Importing Developing Countries"."Ethiopia PDR"
"Net Food Importing Developing Countries"."Gabon"
"Net Food Importing Developing Countries"."Gambia"
"Net Food Importing Developing Countries"."Grenada"
"Net Food Importing Developing Countries"."Guinea"
"Net Food Importing Developing Countries"."Guinea-Bissau"
"Net Food Importing Developing Countries"."Haiti"
"Net Food Importing Developing Countries"."Honduras"
"Net Food Importing Developing Countries"."Jamaica"
"Net Food Importing Developing Countries"."Jordan"
"Net Food Importing Developing Countries"."Kenya"
"Net Food Importing Developing Countries"."Kiribati"
"Net Food Importing Developing Countries"."Lao People's Democratic Republic"
"Net Food Importing Developing Countries"."Lesotho"
"Net Food Importing Developing Countries"."Liberia"
"Net Food Importing Developing Countries"."Madagascar"
"Net Food Importing Developing Countries"."Malawi"
"Net Food Importing Developing Countries"."Maldives"
"Net Food Importing Developing Countries"."Mali"
"Net Food Importing Developing Countries"."Mauritania"
"Net Food Importing Developing Countries"."Mauritius"
"Net Food Importing Developing Countries"."Mongolia"
"Net Food Importing Developing Countries"."Morocco"
"Net Food Importing Developing Countries"."Mozambique"
"Net Food Importing Developing Countries"."Myanmar"
"Net Food Importing Developing Countries"."Namibia"
"Net Food Importing Developing Countries"."Nepal"
"Net Food Importing Developing Countries"."Niger"
"Net Food Importing Developing Countries"."Pakistan"
"Net Food Importing Developing Countries"."Peru"
"Net Food Importing Developing Countries"."Rwanda"
"Net Food Importing Developing Countries"."Saint Kitts and Nevis"
"Net Food Importing Developing Countries"."Saint Lucia"
"Net Food Importing Developing Countries"."Saint Vincent and the Grenadines"
"Net Food Importing Developing Countries"."Sao Tome and Principe"
"Net Food Importing Developing Countries"."Senegal"
"Net Food Importing Developing Countries"."Sierra Leone"
"Net Food Importing Developing Countries"."Solomon Islands"
"Net Food Importing Developing Countries"."Somalia"
"Net Food Importing Developing Countries"."South Sudan"
"Net Food Importing Developing Countries"."Sri Lanka"
"Net Food Importing Developing Countries"."Sudan"
*"Net Food Importing Developing Countries"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Net Food Importing Developing Countries"."Swaziland"
"Net Food Importing Developing Countries"."Timor-Leste"
"Net Food Importing Developing Countries"."Togo"
"Net Food Importing Developing Countries"."Trinidad and Tobago"
"Net Food Importing Developing Countries"."Tunisia"
"Net Food Importing Developing Countries"."Tuvalu"
"Net Food Importing Developing Countries"."Uganda"
"Net Food Importing Developing Countries"."United Republic of Tanzania"
"Net Food Importing Developing Countries"."Vanuatu"
"Net Food Importing Developing Countries"."Venezuela (Bolivarian Republic of)"
"Net Food Importing Developing Countries"."Yemen"
"Net Food Importing Developing Countries"."Zambia"
"Northern Africa"."Algeria"
"Northern Africa"."Egypt"
"Northern Africa"."Libya"
"Northern Africa"."Morocco"
"Northern Africa"."Sudan"
*"Northern Africa"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Northern Africa"."Tunisia"
"Northern America"."Bermuda"
"Northern America"."Canada"
"Northern America"."Saint Pierre and Miquelon"
"Northern America"."United States of America"
"Northern Europe"."Denmark"
"Northern Europe"."Estonia"
"Northern Europe"."Faroe Islands"
"Northern Europe"."Finland"
"Northern Europe"."Iceland"
"Northern Europe"."Ireland"
"Northern Europe"."Latvia"
"Northern Europe"."Lithuania"
"Northern Europe"."Norway"
"Northern Europe"."Sweden"
"Northern Europe"."United Kingdom"
"Oceania"."American Samoa"
"Oceania"."Australia"
"Oceania"."Cook Islands"
"Oceania"."Fiji"
"Oceania"."French Polynesia"
"Oceania"."Guam"
"Oceania"."Kiribati"
"Oceania"."Marshall Islands"
"Oceania"."Nauru"
"Oceania"."New Caledonia"
"Oceania"."New Zealand"
"Oceania"."Niue"
"Oceania"."Norfolk Island"
"Oceania"."Pacific Islands Trust Territory"
"Oceania"."Papua New Guinea"
"Oceania"."Samoa"
"Oceania"."Solomon Islands"
"Oceania"."Tonga"
"Oceania"."Tuvalu"
"Oceania"."Vanuatu"
"Polynesia"."American Samoa"
"Polynesia"."Cook Islands"
"Polynesia"."French Polynesia"
"Polynesia"."Niue"
"Polynesia"."Samoa"
"Polynesia"."Tonga"
"Polynesia"."Tuvalu"
"Small Island Developing States"."American Samoa"
"Small Island Developing States"."Antigua and Barbuda"
"Small Island Developing States"."Aruba"
"Small Island Developing States"."Bahamas"
"Small Island Developing States"."Bahrain"
"Small Island Developing States"."Barbados"
"Small Island Developing States"."Belize"
"Small Island Developing States"."Bermuda"
"Small Island Developing States"."British Virgin Islands"
"Small Island Developing States"."Cabo Verde"
"Small Island Developing States"."Cayman Islands"
"Small Island Developing States"."Comoros"
"Small Island Developing States"."Cook Islands"
"Small Island Developing States"."Cuba"
"Small Island Developing States"."Dominica"
"Small Island Developing States"."Dominican Republic"
"Small Island Developing States"."Fiji"
"Small Island Developing States"."French Polynesia"
"Small Island Developing States"."Grenada"
"Small Island Developing States"."Guam"
"Small Island Developing States"."Guinea-Bissau"
"Small Island Developing States"."Guyana"
"Small Island Developing States"."Haiti"
"Small Island Developing States"."Jamaica"
"Small Island Developing States"."Kiribati"
"Small Island Developing States"."Maldives"
"Small Island Developing States"."Mauritius"
"Small Island Developing States"."Nauru"
"Small Island Developing States"."New Caledonia"
"Small Island Developing States"."Niue"
"Small Island Developing States"."Papua New Guinea"
"Small Island Developing States"."Saint Kitts and Nevis"
"Small Island Developing States"."Saint Lucia"
"Small Island Developing States"."Saint Vincent and the Grenadines"
"Small Island Developing States"."Samoa"
"Small Island Developing States"."Sao Tome and Principe"
"Small Island Developing States"."Seychelles"
"Small Island Developing States"."Singapore"
"Small Island Developing States"."Solomon Islands"
"Small Island Developing States"."Suriname"
"Small Island Developing States"."Timor-Leste"
"Small Island Developing States"."Tonga"
"Small Island Developing States"."Trinidad and Tobago"
"Small Island Developing States"."Tuvalu"
"Small Island Developing States"."Vanuatu"
"South America"."Argentina"
"South America"."Bolivia (Plurinational State of)"
"South America"."Brazil"
"South America"."Chile"
"South America"."Colombia"
"South America"."Ecuador"
"South America"."Falkland Islands (Malvinas)"
"South America"."Guyana"
"South America"."Paraguay"
"South America"."Peru"
"South America"."Suriname"
"South America"."Uruguay"
"South America"."Venezuela (Bolivarian Republic of)"
"South-Eastern Asia"."Brunei Darussalam"
"South-Eastern Asia"."Cambodia"
"South-Eastern Asia"."Indonesia"
"South-Eastern Asia"."Lao People's Democratic Republic"
"South-Eastern Asia"."Malaysia"
"South-Eastern Asia"."Myanmar"
"South-Eastern Asia"."Philippines"
"South-Eastern Asia"."Singapore"
"South-Eastern Asia"."Thailand"
"South-Eastern Asia"."Timor-Leste"
"South-Eastern Asia"."Viet Nam"
"Southern Africa"."Botswana"
"Southern Africa"."Lesotho"
"Southern Africa"."Namibia"
"Southern Africa"."South Africa"
"Southern Africa"."Swaziland"
"Southern Asia"."Afghanistan"
"Southern Asia"."Bangladesh"
"Southern Asia"."Bhutan"
"Southern Asia"."India"
"Southern Asia"."Iran (Islamic Republic of)"
"Southern Asia"."Maldives"
"Southern Asia"."Nepal"
"Southern Asia"."Pakistan"
"Southern Asia"."Sri Lanka"
"Southern Europe"."Albania"
"Southern Europe"."Bosnia and Herzegovina"
"Southern Europe"."Croatia"
"Southern Europe"."Greece"
"Southern Europe"."Italy"
"Southern Europe"."Malta"
"Southern Europe"."Montenegro"
"Southern Europe"."Portugal"
"Southern Europe"."Serbia"
"Southern Europe"."Serbia and Montenegro"
"Southern Europe"."Slovenia"
"Southern Europe"."Spain"
"Southern Europe"."The former Yugoslav Republic of Macedonia"
"Southern Europe"."Yugoslav SFR"
"Western Africa"."Benin"
"Western Africa"."Burkina Faso"
"Western Africa"."Cabo Verde"
"Western Africa"."Côte d'Ivoire"
"Western Africa"."Gambia"
"Western Africa"."Ghana"
"Western Africa"."Guinea"
"Western Africa"."Guinea-Bissau"
"Western Africa"."Liberia"
"Western Africa"."Mali"
"Western Africa"."Mauritania"
"Western Africa"."Niger"
"Western Africa"."Nigeria"
"Western Africa"."Senegal"
"Western Africa"."Sierra Leone"
"Western Africa"."Togo"
"Western Asia"."Armenia"
"Western Asia"."Azerbaijan"
"Western Asia"."Bahrain"
"Western Asia"."Cyprus"
"Western Asia"."Georgia"
"Western Asia"."Iraq"
"Western Asia"."Israel"
"Western Asia"."Jordan"
"Western Asia"."Kuwait"
"Western Asia"."Lebanon"
"Western Asia"."Occupied Palestinian Territory"
"Western Asia"."Oman"
"Western Asia"."Qatar"
"Western Asia"."Saudi Arabia"
"Western Asia"."Syrian Arab Republic"
"Western Asia"."Turkey"
"Western Asia"."United Arab Emirates"
"Western Asia"."Yemen"
"Western Europe"."Austria"
"Western Europe"."Belgium"
"Western Europe"."Belgium-Luxembourg"
"Western Europe"."France"
"Western Europe"."Germany"
"Western Europe"."Luxembourg"
"Western Europe"."Netherlands"
"Western Europe"."Switzerland"
"World"."Afghanistan"
"World"."Albania"
"World"."Algeria"
"World"."American Samoa"
"World"."Angola"
"World"."Antigua and Barbuda"
"World"."Argentina"
"World"."Armenia"
"World"."Aruba"
"World"."Australia"
"World"."Austria"
"World"."Azerbaijan"
"World"."Bahamas"
"World"."Bahrain"
"World"."Bangladesh"
"World"."Barbados"
"World"."Belarus"
"World"."Belgium"
"World"."Belgium-Luxembourg"
"World"."Belize"
"World"."Benin"
"World"."Bermuda"
"World"."Bhutan"
"World"."Bolivia (Plurinational State of)"
"World"."Bosnia and Herzegovina"
"World"."Botswana"
"World"."Brazil"
"World"."British Virgin Islands"
"World"."Brunei Darussalam"
"World"."Bulgaria"
"World"."Burkina Faso"
"World"."Burundi"
"World"."Cabo Verde"
"World"."Cambodia"
"World"."Cameroon"
"World"."Canada"
"World"."Cayman Islands"
"World"."Central African Republic"
"World"."Chad"
"World"."Chile"
"World"."China"
*"World"."China, Hong Kong SAR"
*"World"."China, Macao SAR"
*"World"."China, mainland"
*"World"."China, Taiwan Province of"
"World"."Colombia"
"World"."Comoros"
"World"."Congo"
"World"."Cook Islands"
"World"."Costa Rica"
"World"."Côte d'Ivoire"
"World"."Croatia"
"World"."Cuba"
"World"."Cyprus"
"World"."Czechia"
"World"."Czechoslovakia"
"World"."Democratic People's Republic of Korea"
"World"."Democratic Republic of the Congo"
"World"."Denmark"
"World"."Djibouti"
"World"."Dominica"
"World"."Dominican Republic"
"World"."Ecuador"
"World"."Egypt"
"World"."El Salvador"
"World"."Equatorial Guinea"
"World"."Eritrea"
"World"."Estonia"
"World"."Ethiopia"
"World"."Ethiopia PDR"
"World"."Falkland Islands (Malvinas)"
"World"."Faroe Islands"
"World"."Fiji"
"World"."Finland"
"World"."France"
"World"."French Polynesia"
"World"."Gabon"
"World"."Gambia"
"World"."Georgia"
"World"."Germany"
"World"."Ghana"
"World"."Greece"
"World"."Grenada"
"World"."Guam"
"World"."Guatemala"
"World"."Guinea"
"World"."Guinea-Bissau"
"World"."Guyana"
"World"."Haiti"
"World"."Honduras"
"World"."Hungary"
"World"."Iceland"
"World"."India"
"World"."Indonesia"
"World"."Iran (Islamic Republic of)"
"World"."Iraq"
"World"."Ireland"
"World"."Israel"
"World"."Italy"
"World"."Jamaica"
"World"."Japan"
"World"."Jordan"
"World"."Kazakhstan"
"World"."Kenya"
"World"."Kiribati"
"World"."Kuwait"
"World"."Kyrgyzstan"
"World"."Lao People's Democratic Republic"
"World"."Latvia"
"World"."Lebanon"
"World"."Lesotho"
"World"."Liberia"
"World"."Libya"
"World"."Lithuania"
"World"."Luxembourg"
"World"."Madagascar"
"World"."Malawi"
"World"."Malaysia"
"World"."Maldives"
"World"."Mali"
"World"."Malta"
"World"."Marshall Islands"
"World"."Mauritania"
"World"."Mauritius"
"World"."Mexico"
"World"."Mongolia"
"World"."Montenegro"
"World"."Morocco"
"World"."Mozambique"
"World"."Myanmar"
"World"."Namibia"
"World"."Nauru"
"World"."Nepal"
"World"."Netherlands"
"World"."Netherlands Antilles (former)"
"World"."New Caledonia"
"World"."New Zealand"
"World"."Nicaragua"
"World"."Niger"
"World"."Nigeria"
"World"."Niue"
"World"."Norfolk Island"
"World"."Norway"
"World"."Occupied Palestinian Territory"
"World"."Oman"
"World"."Pacific Islands Trust Territory"
"World"."Pakistan"
"World"."Panama"
"World"."Papua New Guinea"
"World"."Paraguay"
"World"."Peru"
"World"."Philippines"
"World"."Poland"
"World"."Portugal"
"World"."Qatar"
"World"."Republic of Korea"
"World"."Republic of Moldova"
"World"."Romania"
"World"."Russian Federation"
"World"."Rwanda"
"World"."Saint Kitts and Nevis"
"World"."Saint Lucia"
"World"."Saint Pierre and Miquelon"
"World"."Saint Vincent and the Grenadines"
"World"."Samoa"
"World"."Sao Tome and Principe"
"World"."Saudi Arabia"
"World"."Senegal"
"World"."Serbia"
"World"."Serbia and Montenegro"
"World"."Seychelles"
"World"."Sierra Leone"
"World"."Singapore"
"World"."Slovakia"
"World"."Slovenia"
"World"."Solomon Islands"
"World"."Somalia"
"World"."South Africa"
"World"."South Sudan"
"World"."Spain"
"World"."Sri Lanka"
"World"."Sudan"
*"World"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"World"."Suriname"
"World"."Swaziland"
"World"."Sweden"
"World"."Switzerland"
"World"."Syrian Arab Republic"
"World"."Tajikistan"
"World"."Thailand"
"World"."The former Yugoslav Republic of Macedonia"
"World"."Timor-Leste"
"World"."Togo"
"World"."Tonga"
"World"."Trinidad and Tobago"
"World"."Tunisia"
"World"."Turkey"
"World"."Turkmenistan"
"World"."Tuvalu"
"World"."Uganda"
"World"."Ukraine"
"World"."United Arab Emirates"
"World"."United Kingdom"
"World"."United Republic of Tanzania"
"World"."United States of America"
"World"."Uruguay"
"World"."USSR"
"World"."Uzbekistan"
"World"."Vanuatu"
"World"."Venezuela (Bolivarian Republic of)"
"World"."Viet Nam"
"World"."Yemen"
"World"."Yugoslav SFR"
"World"."Zambia"
"World"."Zimbabwe"

*and assign developing and developed countries
*not provided by FAOSTAT, but needed for IPCC, for example, and others

"Developed Countries"."Albania"
"Developed Countries"."Armenia"
"Developed Countries"."Australia"
"Developed Countries"."Austria"
"Developed Countries"."Azerbaijan"
"Developed Countries"."Belarus"
"Developed Countries"."Belgium"
"Developed Countries"."Belgium-Luxembourg"
"Developed Countries"."Bosnia and Herzegovina"
"Developed Countries"."Bulgaria"
"Developed Countries"."Canada"
"Developed Countries"."Croatia"
"Developed Countries"."Czechia"
"Developed Countries"."Czechoslovakia"
"Developed Countries"."Denmark"
"Developed Countries"."Estonia"
"Developed Countries"."Faroe Islands"
"Developed Countries"."Finland"
"Developed Countries"."France"
"Developed Countries"."Georgia"
"Developed Countries"."Germany"
"Developed Countries"."Greece"
"Developed Countries"."Hungary"
"Developed Countries"."Iceland"
"Developed Countries"."Ireland"
"Developed Countries"."Italy"
"Developed Countries"."Japan"
"Developed Countries"."Kazakhstan"
"Developed Countries"."Kyrgyzstan"
"Developed Countries"."Latvia"
"Developed Countries"."Lithuania"
"Developed Countries"."Luxembourg"
"Developed Countries"."Malta"
"Developed Countries"."Montenegro"
"Developed Countries"."Netherlands"
"Developed Countries"."New Zealand"
"Developed Countries"."Norway"
"Developed Countries"."Poland"
"Developed Countries"."Portugal"
"Developed Countries"."Republic of Moldova"
"Developed Countries"."Romania"
"Developed Countries"."Russian Federation"
"Developed Countries"."Serbia"
"Developed Countries"."Serbia and Montenegro"
"Developed Countries"."Slovakia"
"Developed Countries"."Slovenia"
"Developed Countries"."South Africa"
"Developed Countries"."Spain"
"Developed Countries"."Sweden"
"Developed Countries"."Switzerland"
"Developed Countries"."Tajikistan"
"Developed Countries"."The former Yugoslav Republic of Macedonia"
"Developed Countries"."Turkmenistan"
"Developed Countries"."Ukraine"
"Developed Countries"."United Kingdom"
"Developed Countries"."United States of America"
"Developed Countries"."USSR"
"Developed Countries"."Uzbekistan"
"Developed Countries"."Yugoslav SFR"

"Developing Countries"."Afghanistan"
"Developing Countries"."Algeria"
"Developing Countries"."American Samoa"
"Developing Countries"."Angola"
"Developing Countries"."Antigua and Barbuda"
"Developing Countries"."Argentina"
"Developing Countries"."Aruba"
"Developing Countries"."Bahamas"
"Developing Countries"."Bahrain"
"Developing Countries"."Bangladesh"
"Developing Countries"."Barbados"
"Developing Countries"."Belize"
"Developing Countries"."Benin"
"Developing Countries"."Bermuda"
"Developing Countries"."Bhutan"
"Developing Countries"."Bolivia (Plurinational State of)"
"Developing Countries"."Botswana"
"Developing Countries"."Brazil"
"Developing Countries"."British Virgin Islands"
"Developing Countries"."Brunei Darussalam"
"Developing Countries"."Burkina Faso"
"Developing Countries"."Burundi"
"Developing Countries"."Cabo Verde"
"Developing Countries"."Cambodia"
"Developing Countries"."Cameroon"
"Developing Countries"."Cayman Islands"
"Developing Countries"."Central African Republic"
"Developing Countries"."Chad"
"Developing Countries"."Chile"
"Developing Countries"."China"
*"Developing Countries"."China, Hong Kong SAR"
*"Developing Countries"."China, Macao SAR"
*"Developing Countries"."China, mainland"
*"Developing Countries"."China, Taiwan Province of"
"Developing Countries"."Colombia"
"Developing Countries"."Comoros"
"Developing Countries"."Congo"
"Developing Countries"."Cook Islands"
"Developing Countries"."Costa Rica"
"Developing Countries"."Côte d'Ivoire"
"Developing Countries"."Cuba"
"Developing Countries"."Cyprus"
"Developing Countries"."Democratic People's Republic of Korea"
"Developing Countries"."Democratic Republic of the Congo"
"Developing Countries"."Djibouti"
"Developing Countries"."Dominica"
"Developing Countries"."Dominican Republic"
"Developing Countries"."Ecuador"
"Developing Countries"."Egypt"
"Developing Countries"."El Salvador"
"Developing Countries"."Equatorial Guinea"
"Developing Countries"."Eritrea"
"Developing Countries"."Ethiopia"
"Developing Countries"."Ethiopia PDR"
"Developing Countries"."Falkland Islands (Malvinas)"
"Developing Countries"."Fiji"
"Developing Countries"."French Polynesia"
"Developing Countries"."Gabon"
"Developing Countries"."Gambia"
"Developing Countries"."Ghana"
"Developing Countries"."Grenada"
"Developing Countries"."Guam"
"Developing Countries"."Guatemala"
"Developing Countries"."Guinea"
"Developing Countries"."Guinea-Bissau"
"Developing Countries"."Guyana"
"Developing Countries"."Haiti"
"Developing Countries"."Honduras"
"Developing Countries"."India"
"Developing Countries"."Indonesia"
"Developing Countries"."Iran (Islamic Republic of)"
"Developing Countries"."Iraq"
"Developing Countries"."Israel"
"Developing Countries"."Jamaica"
"Developing Countries"."Jordan"
"Developing Countries"."Kenya"
"Developing Countries"."Kiribati"
"Developing Countries"."Kuwait"
"Developing Countries"."Lao People's Democratic Republic"
"Developing Countries"."Lebanon"
"Developing Countries"."Lesotho"
"Developing Countries"."Liberia"
"Developing Countries"."Libya"
"Developing Countries"."Madagascar"
"Developing Countries"."Malawi"
"Developing Countries"."Malaysia"
"Developing Countries"."Maldives"
"Developing Countries"."Mali"
"Developing Countries"."Marshall Islands"
"Developing Countries"."Mauritania"
"Developing Countries"."Mauritius"
"Developing Countries"."Mexico"
"Developing Countries"."Mongolia"
"Developing Countries"."Morocco"
"Developing Countries"."Mozambique"
"Developing Countries"."Myanmar"
"Developing Countries"."Namibia"
"Developing Countries"."Nauru"
"Developing Countries"."Nepal"
"Developing Countries"."Netherlands Antilles (former)"
"Developing Countries"."New Caledonia"
"Developing Countries"."Nicaragua"
"Developing Countries"."Niger"
"Developing Countries"."Nigeria"
"Developing Countries"."Niue"
"Developing Countries"."Norfolk Island"
"Developing Countries"."Occupied Palestinian Territory"
"Developing Countries"."Oman"
"Developing Countries"."Pacific Islands Trust Territory"
"Developing Countries"."Pakistan"
"Developing Countries"."Panama"
"Developing Countries"."Papua New Guinea"
"Developing Countries"."Paraguay"
"Developing Countries"."Peru"
"Developing Countries"."Philippines"
"Developing Countries"."Qatar"
"Developing Countries"."Republic of Korea"
"Developing Countries"."Rwanda"
"Developing Countries"."Saint Kitts and Nevis"
"Developing Countries"."Saint Lucia"
"Developing Countries"."Saint Pierre and Miquelon"
"Developing Countries"."Saint Vincent and the Grenadines"
"Developing Countries"."Samoa"
"Developing Countries"."Sao Tome and Principe"
"Developing Countries"."Saudi Arabia"
"Developing Countries"."Senegal"
"Developing Countries"."Seychelles"
"Developing Countries"."Sierra Leone"
"Developing Countries"."Singapore"
"Developing Countries"."Solomon Islands"
"Developing Countries"."Somalia"
"Developing Countries"."South Sudan"
"Developing Countries"."Sri Lanka"
"Developing Countries"."Sudan"
*"Developing Countries"."Sudan (former)"
*end: 2011 - drop everywhere, as we have a baseline from 2008-2012 and then we double count Sudan - as any new baseline will be more recent, this is no problem, as we then anyway would not have Sudan (former) anymore
"Developing Countries"."Suriname"
"Developing Countries"."Swaziland"
"Developing Countries"."Syrian Arab Republic"
"Developing Countries"."Thailand"
"Developing Countries"."Timor-Leste"
"Developing Countries"."Togo"
"Developing Countries"."Tonga"
"Developing Countries"."Trinidad and Tobago"
"Developing Countries"."Tunisia"
"Developing Countries"."Turkey"
"Developing Countries"."Tuvalu"
"Developing Countries"."Uganda"
"Developing Countries"."United Arab Emirates"
"Developing Countries"."United Republic of Tanzania"
"Developing Countries"."Uruguay"
"Developing Countries"."Vanuatu"
"Developing Countries"."Venezuela (Bolivarian Republic of)"
"Developing Countries"."Viet Nam"
"Developing Countries"."Yemen"
"Developing Countries"."Zambia"
"Developing Countries"."Zimbabwe"

*and assign Indian Subcontinent
*not provided by FAOSTAT, but needed for IPCC, for example, and others

"Indian Subcontinent".India
"Indian Subcontinent".Bangladesh
"Indian Subcontinent".Bhutan
"Indian Subcontinent".Nepal
"Indian Subcontinent".Pakistan
"Indian Subcontinent"."Sri Lanka"
/;

